project_id = "dstc-matching"

[api]
enabled = true
port = 54321
external_url = "env(SUPABASE_EXTERNAL_URL)"
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.seed]
enabled = false

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[local_smtp]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "env(SITE_URL)"
additional_redirect_urls = [
  "http://localhost:4236",
  "http://localhost:4236/reset-password",
  "https://matching.cteftu.id.vn",
  "https://matching.cteftu.id.vn/reset-password",
]
jwt_expiry = 3600
jwt_secret = "env(JWT_SECRET)"
enable_refresh_token_rotation = true
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1m"

[auth.email.smtp]
enabled = true
host = "env(GOTRUE_SMTP_HOST)"
port = "env(GOTRUE_SMTP_PORT)"
user = "env(GOTRUE_SMTP_USER)"
pass = "env(GOTRUE_SMTP_PASS)"
admin_email = "env(GOTRUE_SMTP_ADMIN_EMAIL)"
sender_name = "env(GOTRUE_SMTP_SENDER_NAME)"

[auth.email.template.confirmation]
subject = "Xác minh email — DSTC Matching"
content_path = "./supabase/templates/confirmation.html"

[auth.external.google]
enabled = true
client_id = "env(GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(GOTRUE_EXTERNAL_GOOGLE_SECRET)"
